---
include:
  - board: eyelash_corne_left
    shield: nice_view_adapter nice_epaper    
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DCONFIG_NICE_OLED_WIDGET_WPM=n -DCONFIG_NICE_OLED_WIDGET_WPM_LUNA=n -DCONFIG_NICE_OLED_WIDGET_HID_INDICATORS=n -DCONFIG_NICE_OLED_WIDGET_HID_INDICATORS_LUNA=n -DCONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS=n -DCONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_LUNA=n
    snippet: studio-rpc-usb-uart
    artifact-name: left_eyelash_corne
  - board: eyelash_corne_right
    shield: nice_view_adapter nice_epaper
    artifact-name: right_eyelash_corne
  #- board: eyelash_corne_left
  #  shield: nice_view
    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  #- board: eyelash_corne_right
  #  shield: nice_view
    #snippet: zmk-usb-logging
  #- board: eyelash_corne_left
  #  shield: nice_view
  #  snippet: studio-rpc-usb-uart
  #  cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  #  artifact-name: eyelash_corne_studio_left
  - board: eyelash_corne_left
    shield: settings_reset
    artifact-name: settings_reset
    #snippet: zmk-usb-logging
