draw_config:
  n_columns: 1
  draw_key_sides: true
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 40.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  svg_extra_style: |
    #----------------------------------------------------
    # MODIFICACIÓN: Estilos CSS para Tema Oscuro.
    # Funcionalidad: Reemplaza los estilos por defecto para aplicar un tema oscuro
    # al SVG y mantiene las reglas de posicionamiento de leyendas existentes.
    #----------------------------------------------------
    svg.keymap {
      font-family: Ubuntu Mono, Inconsolata, Consolas, Liberation Mono, Menlo, monospace;
      font-size: 12px;
      font-weight: bold;
      text-rendering: optimizeLegibility;
      background-color: #222;
    }
    rect.key, rect.combo {
      fill: #444;
      stroke: #888;
      stroke-width: 1;
    }
    text.key, text.combo, text.label {
      fill: #ddd;
    }
    rect.held, rect.combo.held {
        fill: #335;
    }
    .sym_sub_text.tap { translate: -5px 2px; font-size: 20px; }
    .sym_sub_text.shifted { translate: 10px 13px; font-size: 10px; opacity: 1.0; }
    .combo.sym_sub_text.tap { translate: -1px 1px; }
    .combo.sym_sub_text.shifted { translate: 7px 5px; font-size: 10px; opacity: 1.0; }
    .toggle.shifted { translate: -10px 12px; }
    .toggle.hold { translate: 13px -23px; }
    .tap_dance.tap { translate: -7px 0px; font-size: 12px; }
    .tap_dance.shifted { translate: 7px 17px; font-size: 12px; opacity: 1.0; }
    .sym_by_sym.tap { translate: -6px 0px; }
    .sym_by_sym.shifted { translate: 10px 12px; opacity: 1.0; }
    .combo.sym_by_sym.tap { translate: -35px 0px; }
    .combo.sym_by_sym.shifted { translate: 35px 20px; opacity: 1.0; }
    .combo.sym_by_sym.hold { visibility: hidden; }
    .combo.sym_by_sym.hold > path[stroke="none"][fill="none"] { visibility: hidden; }

  shrink_wide_legends: 6
  glyph_tap_size: 18
  glyph_hold_size: 15
  glyph_shifted_size: 15
  glyphs: {}
  glyph_urls:
    tabler: https://unpkg.com/@tabler/icons/icons/outline/{}.svg
    tablerf: https://unpkg.com/@tabler/icons/icons/filled/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
  use_local_cache: true

parse_config:
  mark_alternate_layer_activators: true
  sticky_label: $$mdi:gesture-tap-hold$$
  trans_legend:
    tap: $$mdi:transfer$$
    type: trans

  raw_binding_map:
    # Layers
    "<q 1 BACKSPACE":
      tap:  $$mdi:backspace$$
      hold: '$$mdi:navigation-variant$$'
    "<q 3 TAB":
      tap: $$mdi:keyboard-tab$$
      hold: $$mdi:numeric$$
    "<q 2 SPACE":
      tap: $$mdi:keyboard-space$$
      hold: $$mdi:symbol$$
    "<q 3 ENTER":
      tap: $$mdi:keyboard-return$$
      hold: $$mdi:numeric$$
    "<q 1 DELETE":
      tap: $$mdi:backspace-reverse-outline$$
      hold: $$mdi:navigation-variant$$
    # Home rows
    "&hm LEFT_GUI A":
      tap: 'A'
      shifted: $$mdi:apple-keyboard-command$$
    "&hm LEFT_ALT S":
      tap: 'S'
      shifted: $$mdi:apple-keyboard-option$$
    "&hm LEFT_CONTROL D":
      tap: 'D'
      shifted: $$mdi:apple-keyboard-control$$
    "&hm LEFT_SHIFT F":
      tap: 'F'
      shifted: $$mdi:apple-keyboard-shift$$
    "&hm RIGHT_SHIFT J":
      tap: 'J'
      shifted: $$mdi:apple-keyboard-shift$$
    "&hm RIGHT_CONTROL K":
      tap: 'K'
      shifted: $$mdi:apple-keyboard-control$$
    "&hm RIGHT_ALT L":
      tap: 'L'
      shifted: $$mdi:apple-keyboard-option$$
    # self behaviors
    "&hm LG(LS(V)) P":
      tap: 'P'
      shifted: $$mdi:content-copy$$
    # Mouse
    "&msc SCRL_UP":
      tap: $$mdi:pan-up$$
    "&msc SCRL_DOWN":
      tap: $$mdi:pan-down$$
    "&msc SCRL_LEFT":
      tap: $$mdi:pan-left$$
    "&msc SCRL_RIGHT":
      tap: $$mdi:pan-right$$
    "&mmv MOVE_LEFT":
      tap: $$mdi:menu-left$$
      shifted: $$mdi:mouse$$
    "&mmv MOVE_RIGHT":
      tap: $$mdi:menu-right$$
      shifted: $$mdi:mouse$$
    "&mmv MOVE_UP":
      tap: $$mdi:menu-up$$
      shifted: $$mdi:mouse$$
    "&mmv MOVE_DOWN":
      tap: $$mdi:menu-down$$
      shifted: $$mdi:mouse$$
    "&mkp LCLK":
      tap: $$mdi:mouse-left-click-outline$$
    "&mkp RCLK":
      tap: $$mdi:mouse-right-click-outline$$
    "&mkp MCLK":
      tap: $$mdi:mouse-scroll-wheel$$
    # Modifiers
    "&caps_word": $$mdi:alpha-w-box$$
    "&kt RSHIFT":
      tap: $$mdi:apple-keyboard-shift$$
      hold: $$mdi:toggle-switch$$
    # Empty
    "&none":
      tap: $$mdi:minus-circle-outline$$
      type: none
    # Whitespace
    "&bkspc_del":
      type: backspace
      tap: $$mdi:backspace$$
      shifted: $$mdi:backspace-reverse-outline$$
    # Bluetooth
    "&bt BT_SEL 0":
      shifted: $$mdi:bluetooth-connect$$
      hold: 1
    "&bt BT_SEL 1":
      shifted: $$mdi:bluetooth-connect$$
      hold: 2
    "&bt BT_SEL 2":
      shifted: $$mdi:bluetooth-connect$$
      hold: 3
    "&bt BT_SEL 3":
      shifted: $$mdi:bluetooth-connect$$
      hold: 4
    "&bt BT_SEL 4":
      shifted: $$mdi:bluetooth-connect$$
      hold: 5
    "&out OUT_TOG":
      shifted: $$mdi:usb$$
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$
    "&bt BT_PRV":
      shifted: $$mdi:bluetooth-connect$$
      hold: $$mdi:arrow-up-bold$$
    "&bt BT_NXT":
      shifted: $$mdi:bluetooth-connect$$
      hold: $$mdi:arrow-down-bold$$
    # Reset
    "&sys_reset":
      type: bootloader
      tap: $$mdi:backup-restore$$
    "&bootloader":
      tap: $$mdi:progress-download$$

    #----------------------------------------------------
    # ADICIÓN CORREGIDA: Mapeado de comportamientos y macros personalizados.
    # Funcionalidad: Usa expresiones regulares (con el prefijo "re:") para
    # interpretar correctamente los behaviors personalizados y asignar leyendas simples
    # a las teclas en el SVG.
    #----------------------------------------------------
    "re:&shortcut ([^\\s]+) ([^\\s]+)":
      type: tap_dance
      hold: "{0}"
      tap: "{1}"
    "re:&tilde_kp ([^\\s]+) [^\\s]+":
      type: tap_dance
      tap: "{0}"
      hold: "~"
    "re:&kp_bt (\\d+) (\\w+)":
      type: tap_dance
      tap: "{1}"
      hold: "{0}"
      shifted: "$$mdi:bluetooth-connect$$"
    "&Back_Del":
      type: backspace
      tap: $$mdi:backspace$$
      shifted: $$mdi:backspace-reverse-outline$$
    "(ZMK HID USAGE(HID USAGE KEY, HID USAGE KEY KEYBOARD SEMICOLON AND COLON))":
      tap: ";"
      shifted: ":"
    "((LS(ZMK HID USAGE(HID USAGE KEY, HID USAGE KEY KEYBOARD 8 AND ASTERISK))))":
      tap: "("
    "((LS(ZMK HID USAGE(HID USAGE KEY, HID USAGE KEY KEYBOARD 9 AND LEFT PARENTHESIS))))":
      tap: ")"
    "(ZMK HID USAGE(HID USAGE KEY, HID USAGE KEY KEYBOARD EQUAL AND PLUS))":
      tap: "="
      shifted: "+"
    "(LS(ZMK HID USAGE(HID USAGE KEY, HID USAGE KEY KEYBOARD MINUS AND UNDERSCORE)))":
      tap: "_"

  # ZMK
  zmk_keycode_map:
    # Symbols
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL:
      tap: "="
      shifted: "+"
    PLUS: +
    MINUS:
      tap: "-"
      shifted: "_"
    UNDERSCORE: _
    UNDER: _
    SLASH:
      tap: "/"
      shifted: "?"
    FSLH:
      tap: "/"
      shifted: "?"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH:
      tap: '\'
      shifted: "|"
    BSLH:
      tap: '\'
      shifted: "|"
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON:
      tap: ";"
      shifted: ":"
    SEMI:
      tap: ";"
      shifted: ":"
    COLON: ":"
    SINGLE_QUOTE:
      tap: "'"
      shifted: '"'
    SQT:
      tap: "'"
      shifted: '"'
    APOSTROPHE: <
    APOS: .
    DOUBLE_QUOTES: '"'
    DQT: '"'

    LESS_THAN: <
    LT: <
    PERIOD: '.'
    DOT:
      tap: "."
      shifted: ">"
    COMMA:
      tap: ","
      shifted: "<"
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET:
      tap: "["
      shifted: "{"
    LBKT:
      tap: "["
      shifted: "{"
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET:
      tap: "]"
      shifted: "}"
    RBKT:
      tap: "]"
      shifted: "}"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE:
      tap: "`"
      shifted: "~"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"

    # Numbers
    N1:
      tap: 1
      shifted: "!"
    N2:
      tap: 2
      shifted: "@"
    N3:
      tap: 3
      shifted: "#"
    N4:
      tap: 4
      shifted: "$"
    N5:
      tap: 5
      shifted: "%"
    N6:
      tap: 6
      shifted: "^"
    N7:
      tap: 7
      shifted: "&"
    N8:
      tap: 8
      shifted: "*"
    N9:
      tap: 9
      shifted: "("
    N0:
      tap: 0
      shifted: ")"

    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LEFT_CONTROL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LEFT_ALT: $$mdi:apple-keyboard-option$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LEFT_SHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LCMD: $$mdi:apple-keyboard-command$$
    LG: $$mdi:apple-keyboard-command$$
    LEFT_GUI: $$mdi:apple-keyboard-command$$
    LEFT_COMMAND: $$mdi:apple-keyboard-command$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RIGHT_CONTROL: $$mdi:apple-keyboard-control$$
    RALT: $$mdi:apple-keyboard-option$$
    RIGHT_ALT: $$mdi:apple-keyboard-option$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RIGHT_SHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RCMD: $$mdi:apple-keyboard-command$$
    RG: $$mdi:apple-keyboard-command$$
    PSCRN: $$mdi:printer-outline$$
    RIGHT_COMMAND: $$mdi:apple-keyboard-command$$
    PAGE_UP:
      tap: 'PgUp'
    PAGE_DOWN:
      tap: 'PgDn'
    INSERT:
       tap: 'Ins'
    # "Meh" key
    LS(LC(LALT)): $$mdi:star-three-points$$

    # Arrows
    UP: $$mdi:arrow-up-bold$$
    UP_ARROW: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    DOWN_ARROW: $$mdi:arrow-down-bold$$
    LEFT_ARROW: $$mdi:arrow-left-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$
    RIGHT_ARROW: $$mdi:arrow-right-bold$$

    # Whitespace
    ENTER:
      type: enter
      tap: $$mdi:keyboard-return$$
    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    ESCAPE: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    # Locks
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$

    # Sound
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$
    C_VOLUME_UP: $$mdi:volume-high$$
    C_VOLUME_DOWN: $$mdi:volume-low$$

    # Media
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$

    # Bluetooth
    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$

    # Settings
    C_BRI_UP: $$mdi:brightness-5$$
    C_BRIGHTNESS_INC: $$mdi:brightness-5$$
    C_BRI_DN: $$mdi:brightness-7$$
    C_BRI_DEC: $$mdi:brightness-7$$
    C_BRIGHTNESS_DEC: $$mdi:brightness-7$$

    # System
    C_POWER: $$mdi:power-standby$$
    C_AL_LOCK: $$mdi:lock$$
    K_CANCEL: $$mdi:close-box$$
    K_FIND: $$mdi:apple-finder$$
    # Command + 
    LG(A):
      tap: 'A'
      hold: $$mdi:apple-keyboard-command$$
    LG(S):
      tap: 'S'
      hold: $$mdi:apple-keyboard-command$$
    LG(D):
      tap: 'D'
      hold: $$mdi:apple-keyboard-command$$
    LG(F):
      tap: 'F'
      hold: $$mdi:apple-keyboard-command$$
    LG(Z):
      tap: 'Z'
      hold: $$mdi:apple-keyboard-command$$
    LG(X):
      tap: 'X'
      hold: $$mdi:apple-keyboard-command$$
    LG(C):
      tap: 'C'
      hold: $$mdi:apple-keyboard-command$$
    LG(V):
      tap: 'V'
      hold: $$mdi:apple-keyboard-command$$
    # Zoom
    RG(RS(A)):
      tap: $$mdi:microphone$$
      hold: zoom
    RG(RS(V)):
      tap: $$mdi:video$$
      hold: zoom

  zmk_combos:
    combo_to_2:
      align: top
    combo_to_3:
      align: top
    combo_bt_clear:
      align: top
      offset: 0.03
    combo_mute:
      align: top
      offset: 0.15
    combo_minus:
      key:
        shifted: "_"
        hold: "-"
    combo_equal:
      key:
        shifted: "+"
        hold: "="
    combo_backslash:
      key:
        shifted: "|"
        hold: \
    combo_lbkt:
      key:
        shifted: "{"
        hold: "["
    combo_rbkt:
      key:
        shifted: "}"
        hold: "]"
    combo_semicolon:
      key:
        shifted: ":"
        hold: ";"
