# --- INICIO: draw_config ---
draw_config:
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: auto
  n_columns: 1
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  draw_key_sides: false
  svg_extra_style: ''
  footer_text: Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
  glyph_urls:
    tabler: https://unpkg.com/@tabler/icons/icons/outline/{}.svg
    tablerf: https://unpkg.com/@tabler/icons/icons/filled/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
  use_local_cache: true
# --- FIN: draw_config ---

parse_config:
  mark_alternate_layer_activators: true
  sticky_label: $$mdi:gesture-tap-hold$$
  trans_legend:
    tap: $$mdi:transfer$$
    type: trans

  raw_binding_map:
# --- INICIO: Mapeo de behaviors mejorado y completo ---

    # 1. Reglas explícitas para atajos comunes con íconos MDI.
    "&shortcut LC(C) C": { tap: 'C', hold: '$$mdi:content-copy$$' }
    "&shortcut LC(V) V": { tap: 'V', hold: '$$mdi:content-paste$$' }
    "&shortcut LC(X) X": { tap: 'X', hold: '$$mdi:content-cut$$' }
    "&shortcut LC(Z) Z": { tap: 'Z', hold: '$$mdi:undo$$' }
    "&shortcut LC(Y) Y": { tap: 'Y', hold: '$$mdi:redo$$' }
    "&shortcut LC(F) F": { tap: 'F', hold: '$$mdi:magnify$$' }
    "&shortcut LC(T) T": { tap: 'T', hold: '$$mdi:tab-plus$$' }
    "&shortcut LG(LS(S)) S": { tap: 'S', hold: '$$mdi:camera-outline$$' }
    "&shortcut C_AL_MAIL M": { tap: 'M', hold: '$$mdi:email-outline$$' }
    "&shortcut ES_LT ES_COMMA": { tap: ',', hold: '<' }
    "&shortcut ES_GT ES_DOT": { tap: '.', hold: '>' }
    "&shortcut ES_AT Q": { tap: 'Q', hold: '@' }
    "&shortcut C_REWIND K_PREVIOUS": { tap: '$$mdi:skip-previous$$', hold: '$$mdi:rewind$$' }
    "&shortcut C_FAST_FORWARD K_NEXT": { tap: '$$mdi:skip-next$$', hold: '$$mdi:fast-forward$$' }
    "&shortcut LA(LC(F1)) F1": { tap: 'F1', hold: '$$mdi:monitor-dashboard$$' }
    "&shortcut LC(LA(F2)) F2": { tap: 'F2', hold: '$$mdi:monitor-dashboard$$' }
    "&shortcut LC(LA(F3)) F3": { tap: 'F3', hold: '$$mdi:monitor-dashboard$$' }
    "&shortcut LC(LA(F4)) F4": { tap: 'F4', hold: '$$mdi:monitor-dashboard$$' }

    # 2. Mapeo para la capa de símbolos (SYM_NUM).
    "&shortcut ES_IEXCL ES_EXCL": { tap: '!', hold: '¡' }
    "&shortcut ES_SQT ES_DQT": { tap: '"', hold: "'" }
    "&shortcut ES_BSLH ES_SLASH": { tap: '/', hold: '\' }
    "&shortcut ES_LBRC ES_LPAR": { tap: '(', hold: '{' }
    "&shortcut ES_RBRC ES_RPAR": { tap: ')', hold: '}' }
    "&shortcut ES_DEG ES_PIPE": { tap: '|', hold: '°' }
    "&shortcut ES_TILDE ES_NOT": { tap: '¬', hold: '~' }
    "&shortcut ES_IQMARK ES_QMARK": { tap: '?', hold: '¿' }
    "&shortcut ES_COLON KP_DOT": { tap: '.', hold: ':' }
    "&shortcut ES_EQUAL KP_ENTER": { tap: '$$mdi:keyboard-return$$', hold: '=' }
    "&shortcut ES_HASH N0": { tap: '0', hold: '#' }
    "&shortcut ES_PERCENT DOT": { tap: '.', hold: '%' }

    # 3. Reglas explícitas para &tilde_kp con lógica invertida.
    "&tilde_kp A A": { tap: 'A', hold: 'Á' }
    "&tilde_kp E E": { tap: 'E', hold: 'É' }
    "&tilde_kp I I": { tap: 'I', hold: 'Í' }
    "&tilde_kp O O": { tap: 'O', hold: 'Ó' }
    "&tilde_kp U U": { tap: 'U', hold: 'Ú' }
    
    # 4. Reglas para behaviors especiales.
    "&soft_off": { tap: '$$mdi:power-sleep$$' }
    "&rgb_ug RGB_BRI": { tap: '$$mdi:brightness-plus$$' }
    "&rgb_ug RGB_BRD": { tap: '$$mdi:brightness-minus$$' }
    "&rgb_ug RGB_TOG": { tap: '$$mdi:lightbulb-on-off$$' }
    "&rgb_ug RGB_EFF": { tap: '$$mdi:palette-swatch-variant$$' }
    "&rgb_ug RGB_EFR": { tap: '$$mdi:rotate-3d-variant$$' }
    "&Back_Del": { tap: 'Bksp', shifted: 'Del' }

    # 5. Reglas genéricas para behaviors comunes.
    r"^&shortcut (.*?) (.*?)$": { tap: '\2', hold: '\1' }
    r"^&hrm (.*?) (.*?)$": { tap: '\2', hold: '\1' }
    r"^<_hold (\d+) (.*?)$": { tap: '\2', hold: 'L\1' }
    r"^< (\d+) (.*?)$": { tap: '\2', hold: 'L\1' }
    r"^&mt (.*?) (.*?)$": { tap: '\2', hold: '\1' }
    r"^&mo (\d+)$": { tap: 'L\1' }
    r"^&kp_bt (\d+) (.*?)$": { tap: '\2', hold: 'BT\1' }

# --- FIN: Mapeo de behaviors mejorado y completo ---

    # Mapeos estándar
    "&none": { type: none, tap: $$mdi:minus-circle-outline$$ }
    "&bootloader": { tap: $$mdi:progress-download$$ }
    "&out OUT_TOG": { shifted: $$mdi:usb$$, tap: $$mdi:toggle-switch$$, hold: $$mdi:bluetooth$$ }

  # ZMK
  zmk_keycode_map:
# --- INICIO: Alias completos para todas las capas ---
    # Este bloque garantiza que todos los keycodes personalizados se representen correctamente.
    ES_HASH: "#"
    ES_DLLR: "$"
    ES_PRCNT: "%"
    ES_AMPS: "&"
    ES_EQUAL: "="
    ES_LBKT: "["
    ES_RBKT: "]"
    ES_N_TILDE: "Ñ"
    ES_MINUS: "-"
    ES_STAR: "*"
    ES_AT: "@"
    K_APP: $$mdi:menu$$
    K_PLAY_PAUSE: $$mdi:play-pause$$
    K_MUTE2: $$mdi:volume-mute$$
    K_VOLUME_UP2: $$mdi:volume-plus$$
    K_VOLUME_DOWN2: $$mdi:volume-minus$$
    F1: "F1"
    F2: "F2"
    F3: "F3"
    F4: "F4"
    F5: "F5"
    F6: "F6"
    F7: "F7"
    F8: "F8"
    F9: "F9"
    F10: "F10"
    F11: "F11"
    F12: "F12"
    F13: "F13"
    F14: "F14"
    F15: "F15"
    F16: "F16"
    F17: "F17"
    F18: "F18"
    F19: "F19"
    F20: "F20"
    F21: "F21"
    F22: "F22"
    F23: "F23"
    F24: "F24"
# --- FIN: Alias completos para todas las capas ---

    # Symbols
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    # AT: "@" # Comentado para evitar conflicto con ES_AT
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL:
      tap: "="
      shifted: "+"
    PLUS: +
    MINUS:
      tap: "-"
      shifted: "_"
    UNDERSCORE: _
    UNDER: _
    SLASH:
      tap: "/"
      shifted: "?"
    FSLH:
      tap: "/"
      shifted: "?"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH:
      tap: '\'
      shifted: "|"
    BSLH:
      tap: '\'
      shifted: "|"
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON:
      tap: ";"
      shifted: ":"
    SEMI:
      tap: ";"
      shifted: ":"
    COLON: ":"
    SINGLE_QUOTE:
      tap: "'"
      shifted: '"'
    SQT:
      tap: "'"
      shifted: '"'
    APOSTROPHE: <
    APOS: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    LESS_THAN: <
    LT: <
    PERIOD: '.'
    DOT:
      tap: "."
      shifted: ">"
    COMMA:
      tap: ","
      shifted: "<"
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET:
      tap: "["
      shifted: "{"
    LBKT:
      tap: "["
      shifted: "{"
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET:
      tap: "]"
      shifted: "}"
    RBKT:
      tap: "]"
      shifted: "}"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE:
      tap: "`"
      shifted: "~"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"

    # Numbers
    N1: { tap: 1, shifted: "!" }
    N2: { tap: 2, shifted: "@" }
    N3: { tap: 3, shifted: "#" }
    N4: { tap: 4, shifted: "$" }
    N5: { tap: 5, shifted: "%" }
    N6: { tap: 6, shifted: "^" }
    N7: { tap: 7, shifted: "&" }
    N8: { tap: 8, shifted: "*" }
    N9: { tap: 9, shifted: "(" }
    N0: { tap: 0, shifted: ")" }

    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LEFT_CONTROL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LEFT_ALT: $$mdi:apple-keyboard-option$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LEFT_SHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LCMD: $$mdi:apple-keyboard-command$$
    LG: $$mdi:apple-keyboard-command$$
    LWIN: $$mdi:microsoft-windows$$
    LEFT_GUI: $$mdi:apple-keyboard-command$$
    LEFT_COMMAND: $$mdi:apple-keyboard-command$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RIGHT_CONTROL: $$mdi:apple-keyboard-control$$
    RALT: $$mdi:apple-keyboard-option$$
    RIGHT_ALT: $$mdi:apple-keyboard-option$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RIGHT_SHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RCMD: $$mdi:apple-keyboard-command$$
# --- INICIO: draw_config ---
draw_config:
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: auto
  n_columns: 1
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  draw_key_sides: false
  svg_extra_style: ''
  footer_text: Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
  glyph_urls:
    tabler: https://unpkg.com/@tabler/icons/icons/outline/{}.svg
    tablerf: https://unpkg.com/@tabler/icons/icons/filled/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
  use_local_cache: true
# --- FIN: draw_config ---

parse_config:
  mark_alternate_layer_activators: true
  sticky_label: $$mdi:gesture-tap-hold$$
  trans_legend:
    tap: $$mdi:transfer$$
    type: trans

  raw_binding_map:
# --- INICIO: Mapeo completo y corregido de behaviors ---

    # 1. Reglas explícitas de alta prioridad para atajos y símbolos complejos.
    "&shortcut LC(C) C": { tap: 'C', hold: '$$mdi:content-copy$$' }
    "&shortcut LC(V) V": { tap: 'V', hold: '$$mdi:content-paste$$' }
    "&shortcut LC(X) X": { tap: 'X', hold: '$$mdi:content-cut$$' }
    "&shortcut LC(Z) Z": { tap: 'Z', hold: '$$mdi:undo$$' }
    "&shortcut LC(Y) Y": { tap: 'Y', hold: '$$mdi:redo$$' }
    "&shortcut LC(F) F": { tap: 'F', hold: '$$mdi:magnify$$' }
    "&shortcut LC(T) T": { tap: 'T', hold: '$$mdi:tab-plus$$' }
    "&shortcut LG(LS(S)) S": { tap: 'S', hold: '$$mdi:camera-outline$$' }
    "&shortcut C_AL_MAIL M": { tap: 'M', hold: '$$mdi:email-outline$$' }
    "&shortcut ES_LT ES_COMMA": { tap: ',', hold: '<' }
    "&shortcut ES_GT ES_DOT": { tap: '.', hold: '>' }
    "&shortcut ES_AT Q": { tap: 'Q', hold: '@' }
    "&shortcut C_REWIND K_PREVIOUS": { tap: '$$mdi:skip-previous$$', hold: '$$mdi:rewind$$' }
    "&shortcut C_FAST_FORWARD K_NEXT": { tap: '$$mdi:skip-next$$', hold: '$$mdi:fast-forward$$' }
    "&shortcut LA(LC(F1)) F1": { tap: 'F1', hold: '$$mdi:monitor-dashboard$$' }
    "&shortcut LC(LA(F2)) F2": { tap: 'F2', hold: '$$mdi:monitor-dashboard$$' }
    "&shortcut LC(LA(F3)) F3": { tap: 'F3', hold: '$$mdi:monitor-dashboard$$' }
    "&shortcut LC(LA(F4)) F4": { tap: 'F4', hold: '$$mdi:monitor-dashboard$$' }
    "&shortcut ES_IEXCL ES_EXCL": { tap: '!', hold: '¡' }
    "&shortcut ES_SQT ES_DQT": { tap: '"', hold: "'" }
    "&shortcut ES_BSLH ES_SLASH": { tap: '/', hold: '\' }
    "&shortcut ES_LBRC ES_LPAR": { tap: '(', hold: '{' }
    "&shortcut ES_RBRC ES_RPAR": { tap: ')', hold: '}' }
    "&shortcut ES_DEG ES_PIPE": { tap: '|', hold: '°' }
    "&shortcut ES_TILDE ES_NOT": { tap: '¬', hold: '~' }
    "&shortcut ES_IQMARK ES_QMARK": { tap: '?', hold: '¿' }
    "&shortcut ES_COLON KP_DOT": { tap: '.', hold: ':' }
    "&shortcut ES_EQUAL KP_ENTER": { tap: '$$mdi:keyboard-return$$', hold: '=' }
    "&shortcut ES_HASH N0": { tap: '0', hold: '#' }
    "&shortcut ES_PERCENT DOT": { tap: '.', hold: '%' }
    "&tilde_kp A A": { tap: 'A', hold: 'Á' }
    "&tilde_kp E E": { tap: 'E', hold: 'É' }
    "&tilde_kp I I": { tap: 'I', hold: 'Í' }
    "&tilde_kp O O": { tap: 'O', hold: 'Ó' }
    "&tilde_kp U U": { tap: 'U', hold: 'Ú' }

    # 2. Reglas genéricas para el resto de los behaviors personalizados.
    r"^&shortcut (.*?) (.*?)$": { tap: '\2', hold: '\1' }
    r"^&hrm (.*?) (.*?)$": { tap: '\2', hold: '\1' }
    r"^<_hold (\d+) (.*?)$": { tap: '\2', hold: 'L\1' }
    r"^< (\d+) (.*?)$": { tap: '\2', hold: 'L\1' }
    r"^&mt (.*?) (.*?)$": { tap: '\2', hold: '\1' }
    r"^&mo (\d+)$": { tap: 'L\1' }
    r"^&kp_bt (\d+) (.*?)$": { tap: '\2', hold: 'BT\1' }
    
    # 3. Reglas para behaviors sin parámetros
    "&Back_Del": { tap: 'Bksp', shifted: 'Del' }
    "&soft_off": { tap: '$$mdi:power-sleep$$' }
    "&rgb_ug RGB_BRI": { tap: '$$mdi:brightness-plus$$' }
    "&rgb_ug RGB_BRD": { tap: '$$mdi:brightness-minus$$' }
    "&rgb_ug RGB_TOG": { tap: '$$mdi:lightbulb-on-off$$' }
    "&rgb_ug RGB_EFF": { tap: '$$mdi:palette-swatch-variant$$' }
    "&rgb_ug RGB_EFR": { tap: '$$mdi:rotate-3d-variant$$' }
    "&caps_word": { tap: $$mdi:alpha-w-box$$ }
    "&bootloader": { tap: $$mdi:progress-download$$ }
    "&none": { type: none, tap: $$mdi:minus-circle-outline$$ }

    # 4. Mapeos originales que deben conservarse
    "&out OUT_TOG":
      shifted: $$mdi:usb$$
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$
    "&bt BT_SEL 0":
      shifted: $$mdi:bluetooth-connect$$
      hold: 1
    "&bt BT_SEL 1":
      shifted: $$mdi:bluetooth-connect$$
      hold: 2
    "&bt BT_SEL 2":
      shifted: $$mdi:bluetooth-connect$$
      hold: 3
    "&bt BT_SEL 3":
      shifted: $$mdi:bluetooth-connect$$
      hold: 4
    "&bt BT_SEL 4":
      shifted: $$mdi:bluetooth-connect$$
      hold: 5
    "&msc SCRL_UP":
      tap: $$mdi:pan-up$$
    "&msc SCRL_DOWN":
      tap: $$mdi:pan-down$$
    "&msc SCRL_LEFT":
      tap: $$mdi:pan-left$$
    "&msc SCRL_RIGHT":
      tap: $$mdi:pan-right$$
    "&mmv MOVE_LEFT":
      shifted: $$mdi:mouse$$
      tap: $$mdi:menu-left$$
    "&mmv MOVE_RIGHT":
      shifted: $$mdi:mouse$$
      tap: $$mdi:menu-right$$
    "&mmv MOVE_UP":
      shifted: $$mdi:mouse$$
      tap: $$mdi:menu-up$$
    "&mmv MOVE_DOWN":
      shifted: $$mdi:mouse$$
      tap: $$mdi:menu-down$$
    "&mkp LCLK":
      tap: $$mdi:mouse-left-click-outline$$
    "&mkp RCLK":
      tap: $$mdi:mouse-right-click-outline$$
    "&mkp MCLK":
      tap: $$mdi:mouse-scroll-wheel$$
# --- FIN: Mapeo completo y corregido de behaviors ---

  zmk_keycode_map:
# --- INICIO: Alias completos para todas las capas ---
    ES_HASH: "#"
    ES_DLLR: "$"
    ES_PRCNT: "%"
    ES_AMPS: "&"
    ES_EQUAL: "="
    ES_LBKT: "["
    ES_RBKT: "]"
    ES_N_TILDE: "Ñ"
    ES_MINUS: "-"
    ES_STAR: "*"
    ES_AT: "@"
    K_APP: $$mdi:menu$$
    K_PLAY_PAUSE: $$mdi:play-pause$$
    K_MUTE2: $$mdi:volume-mute$$
    K_VOLUME_UP2: $$mdi:volume-plus$$
    K_VOLUME_DOWN2: $$mdi:volume-minus$$
    C_AL_CALC: $$mdi:calculator$$
    F1: "F1"
    F2: "F2"
    F3: "F3"
    F4: "F4"
    F5: "F5"
    F6: "F6"
    F7: "F7"
    F8: "F8"
    F9: "F9"
    F10: "F10"
    F11: "F11"
    F12: "F12"
    F13: "F13"
    F14: "F14"
    F15: "F15"
    F16: "F16"
    F17: "F17"
    F18: "F18"
    F19: "F19"
    F20: "F20"
    F21: "F21"
    F22: "F22"
    F23: "F23"
    F24: "F24"
# --- FIN: Alias completos para todas las capas ---

    # Symbols
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL:
      tap: "="
      shifted: "+"
    PLUS: +
    MINUS:
      tap: "-"
      shifted: "_"
    UNDERSCORE: _
    UNDER: _
    SLASH:
      tap: "/"
      shifted: "?"
    FSLH:
      tap: "/"
      shifted: "?"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH:
      tap: '\'
      shifted: "|"
    BSLH:
      tap: '\'
      shifted: "|"
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON:
      tap: ";"
      shifted: ":"
    SEMI:
      tap: ";"
      shifted: ":"
    COLON: ":"
    SINGLE_QUOTE:
      tap: "'"
      shifted: '"'
    SQT:
      tap: "'"
      shifted: '"'
    APOSTROPHE: <
    APOS: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    LESS_THAN: <
    LT: <
    PERIOD: '.'
    DOT:
      tap: "."
      shifted: ">"
    COMMA:
      tap: ","
      shifted: "<"
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET:
      tap: "["
      shifted: "{"
    LBKT:
      tap: "["
      shifted: "{"
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET:
      tap: "]"
      shifted: "}"
    RBKT:
      tap: "]"
      shifted: "}"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE:
      tap: "`"
      shifted: "~"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"

    # Numbers
    N1: { tap: 1, shifted: "!" }
    N2: { tap: 2, shifted: "@" }
    N3: { tap: 3, shifted: "#" }
    N4: { tap: 4, shifted: "$" }
    N5: { tap: 5, shifted: "%" }
    N6: { tap: 6, shifted: "^" }
    N7: { tap: 7, shifted: "&" }
    N8: { tap: 8, shifted: "*" }
    N9: { tap: 9, shifted: "(" }
    N0: { tap: 0, shifted: ")" }
    KP_N0: "0"
    KP_N1: "1"
    KP_N2: "2"
    KP_N3: "3"
    KP_N4: "4"
    KP_N5: "5"
    KP_N6: "6"
    KP_N7: "7"
    KP_N8: "8"
    KP_N9: "9"
    KP_PLUS: "+"
    KP_MINUS: "-"
    KP_MULTIPLY: "*"
    KP_DIVIDE: "/"
    KP_DOT: "."
    KP_ENTER: $$mdi:keyboard-return$$

    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LCMD: $$mdi:apple-keyboard-command$$
    LG: $$mdi:apple-keyboard-command$$
    LWIN: $$mdi:microsoft-windows$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RALT: $$mdi:apple-keyboard-option$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RCMD: $$mdi:apple-keyboard-command$$
    RG: $$mdi:apple-keyboard-command$$
    RIGHT_WIN: $$mdi:microsoft-windows$$
    PSCRN: $$mdi:printer-outline$$
    PAGE_UP: 'PgUp'
    PAGE_DOWN: 'PgDn'
    HOME: 'Home'
    END: 'End'
    INSERT: 'Ins'
    LS(LC(LALT)): $$mdi:star-three-points$$

    # Arrows
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$

    # Whitespace
    ENTER: { type: enter, tap: $$mdi:keyboard-return$$ }
    ESC: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE: { type: backspace, tap: $$mdi:backspace$$ }
    BSPC: { type: backspace, tap: $$mdi:backspace$$ }
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    # Locks
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$

    # Sound & Media
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$
    C_FAST_FORWARD: $$mdi:fast-forward$$
    C_REWIND: $$mdi:rewind$$

    # Bluetooth
    BT_CLR: $$mdi:bluetooth-off$$

  zmk_combos:
    combo_to_2: { align: top }
    combo_to_3: { align: top }
    combo_bt_clear: { align: top, offset: 0.03 }
    combo_mute: { align: top, offset: 0.15 }
    combo_minus: { key: { shifted: "_", hold: "-" } }
    combo_equal: { key: { shifted: "+", hold: "=" } }
    combo_backslash: { key: { shifted: "|", hold: \ } }
    combo_lbkt: { key: { shifted: "{", hold: "[" } }
    combo_rbkt: { key: { shifted: "}", hold: "]" } }
    combo_semicolon: { key: { shifted: ":", hold: ";" } }
