draw_config:
  key_w: 60
  key_h: 56
  split_gap: 30.0
  combo_w: 28
  combo_h: 26
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: true
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 40.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4
  svg_extra_style: |
    /* Estilos personalizados del usuario mantenidos */
    /* For default sytles, see https://github.com/caksoylar/keymap-drawer/blob/main/keymap_drawer/config.py#L85 */

    svg.keymap {
      font-family: Ubuntu Mono, Inconsolata, Consolas, Liberation Mono, Menlo, monospace;
      font-size: 12px;
      font-weight: bold;
      text-rendering: optimizeLegibility;
    }

    /* Technique borrowed and extended from https://github.com/englmaxi/zmk-config/blob/master/keymap-drawer/config.yaml */
    .sym_sub_text.tap {
      translate: -5px 2px;
      font-size: 20px;
    }
    .sym_sub_text.shifted {
      translate: 10px 13px;
      font-size: 10px;
      opacity: 1.0;
    }
    .combo.sym_sub_text.tap {
      translate: -1px 1px;
    }
    .combo.sym_sub_text.shifted {
      translate: 7px 5px;
      font-size: 10px;
      opacity: 1.0;
    }

    /* Toggle */
    .toggle.shifted {
      translate: -10px 12px;
    }

    .toggle.hold {
      translate: 13px -23px;
    }

    /* Variant for tap-dances */
    .tap_dance.tap {
      translate: -7px 0px;
      font-size: 12px;
    }
    .tap_dance.shifted {
      translate: 7px 17px;
      font-size: 12px;
      opacity: 1.0;
    }

    /* Variant for symbol next to symbol */
    .sym_by_sym.tap {
      translate: -6px 0px;
    }
    .sym_by_sym.shifted {
      translate: 10px 12px;
      opacity: 1.0;
    }

    .combo.sym_by_sym.tap {
      translate: -35px 0px;
    }
    .combo.sym_by_sym.shifted {
      translate: 35px 20px;
      opacity: 1.0;
    }

    .combo.sym_by_sym.hold {
      visibility: hidden;
    }

    /* hide hold box for combo sym_by_sym */
    .combo.sym_by_sym.hold > path[stroke="none"][fill="none"] {
      visibility: hidden;
    }
  footer_text: ''
  shrink_wide_legends: 8
  style_layer_activators: true
  glyph_tap_size: 18
  glyph_hold_size: 15
  glyph_shifted_size: 15
  glyphs: {}
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:

    # --- KEYCODES PERSONALIZADOS ---
    '&oneshot LC(Y)': $$mdi:redo$$
    '&oneshot LC(Z)': $$mdi:undo$$
    '&oneshot LC(F)': $$mdi:magnify$$
    '&oneshot LC(C)': $$mdi:content-copy$$
    '&oneshot LC(X)': $$mdi:content-cut$$
    '&oneshot LC(V)': $$mdi:content-paste$$
    '&oneshot LC(T)': $$mdi:tab-plus$$
    '&oneshot LG(LS(S))': $$mdi:camera-outline$$
    '&oneshot LS(LG(S))': $$mdi:camera-outline$$
    '&oneshot C_AL_MAIL': $$mdi:email-outline$$

    '&oneshot C_REWIND': $$mdi:rewind$$
    '&oneshot K_REWIND': $$mdi:skip-previous$$
    '&oneshot C_FAST_FORWARD': $$mdi:fast-forward$$
    '&oneshot K_FAST_FORWARD': $$mdi:fast-forward$$
    '&oneshot C_PREVIOUS': $$mdi:skip-previous$$
    '&oneshot K_PREVIOUS': $$mdi:skip-previous$$
    '&oneshot K_NEXT': $$mdi:skip-next$$
    '&oneshot C_NEXT': $$mdi:skip-next$$
    '&oneshot K_PLAY_PAUSE': $$mdi:play-pause$$
    '&oneshot C_PLAY_PAUSE': $$mdi:play-pause$$
    '&oneshot K_PP': $$mdi:play-pause$$
    '&oneshot C_PP': $$mdi:play-pause$$
   
    '&oneshot LA(LC(F1))': 'Ctrl+Alt+F1'
    '&oneshot LA(LC(F2))': 'Ctrl+Alt+F2'
    '&oneshot LA(LC(F3))': 'Ctrl+Alt+F3'
    '&oneshot LA(LC(F4))': 'Ctrl+Alt+F4'
    '&oneshot LC(LA(F1))': 'Ctrl+Alt+F1'
    '&oneshot LC(LA(F2))': 'Ctrl+Alt+F2'
    '&oneshot LC(LA(F3))': 'Ctrl+Alt+F3'
    '&oneshot LC(LA(F4))': 'Ctrl+Alt+F4'

    '&oneshot ES_IEXCL': '¡'
    '&oneshot ES_SQT': "'"
    '&oneshot ES_BSLH': '\'
    '&oneshot ES_LBRC': '{'
    '&oneshot ES_RBRC': '}'
    '&oneshot ES_DEG': '°'
    '&oneshot ES_TILDE': '~'
    '&oneshot ES_IQMARK': '¿'
    '&oneshot ES_COLON': ':'
    '&oneshot ES_EQUAL': '='
    '&oneshot ES_HASH': '#'
    '&oneshot ES_PERCENT': '%'
    '&oneshot ES_AT': '@'
    '&oneshot ES_AT_SIGN': '@'
    '&oneshot ES_NOT': '¬'
    '&oneshot ES_CARET': '^'
    '&oneshot ES_GRAVE': '`'
    '&oneshot ES_LESS_THAN': '<'
    '&oneshot ES_LT': '<'
    '&oneshot ES_GREATER_THAN': '>'
    '&oneshot ES_GT': '>'
    '&oneshot HOME': $$mdi:arrow-collapse-left$$
    '&oneshot END': $$mdi:arrow-collapse-right$$


    '&tilde A': Á
    '&tilde E': É
    '&tilde I': Í
    '&tilde O': Ó
    '&tilde U': Ú
     

    (ZMK HID USAGE(HID USAGE KEY, HID USAGE KEY KEYBOARD SEMICOLON AND COLON)): ;
    (ZMK HID USAGE(HID USAGE KEY, HID USAGE KEY KEYBOARD SLASH AND QUESTION MARK)): /
    (LS(ZMK HID USAGE(HID USAGE KEY, HID USAGE KEY KEYBOARD 3 AND HASH))): '#'
    ((LS(ZMK HID USAGE(HID USAGE KEY, HID USAGE KEY KEYBOARD 4 AND DOLLAR)))): $
    ((LS(ZMK HID USAGE(HID USAGE KEY, HID USAGE KEY KEYBOARD 5 AND PERCENT)))): '%'
    ((LS(ZMK HID USAGE(HID USAGE KEY, HID USAGE KEY KEYBOARD 6 AND CARET)))): ^
    ((LS(ZMK HID USAGE(HID USAGE KEY, HID USAGE KEY KEYBOARD 8 AND ASTERISK)))): '*'
    ((LS(ZMK HID USAGE(HID USAGE KEY, HID USAGE KEY KEYBOARD 9 AND LEFT PARENTHESIS)))): (
    (LS(ZMK HID USAGE(HID USAGE KEY, HID USAGE KEY KEYBOARD 0 AND RIGHT PARENTHESIS))): )


    # Layer-Tap Hold
    '<_hold 3': {tap: '$$mdi:keyboard-return$$', hold: 'Fn'}


    # Mod-Tap
    '&mt LWIN': {tap: '$$mdi:keyboard-tab$$', hold: '$$mdi:microsoft-windows$$'}
   
   
    # Toggles de capa
    '&tog 1': {tap: "$$mdi:keyboard-close$$", type: toggle}
    '&tog 4': {tap: "$$mdi:numeric$$", type: toggle}

   
    # Mod-Morph (Back_Del)
    '&Back_Del': {tap: '$$mdi:backspace$$', shifted: '$$mdi:backspace-reverse-outline$$'}



    # --- KEYCODES DEL SISTEMA ---

    # MOUSE
    '&msc SCRL_LEFT': $$mdi:pan-left$$
    '&msc SCRL_RIGHT': $$mdi:pan-right$$
    '&msc SCRL_UP': $$mdi:pan-up$$
    '&msc SCRL_DOWN': $$mdi:pan-down$$
    '&mmv MOVE_UP': {t: $$mdi:menu-up$$, s: $$mdi:mouse$$}
    '&mmv MOVE_DOWN': {t: $$mdi:menu-down$$, s: $$mdi:mouse$$}
    '&mmv MOVE_LEFT': {t: $$mdi:menu-left$$, s: $$mdi:mouse$$}
    '&mmv MOVE_RIGHT': {t: $$mdi:menu-right$$, s: $$mdi:mouse$$}
    '&mkp LCLK': $$mdi:mouse-left-click-outline$$
    '&mkp RCLK': $$mdi:mouse-right-click-outline$$
    '&mkp MCLK': $$mdi:mouse-scroll-wheel$$
    '&mkp MB4': {t: $$mdi:arrow-u-left-top$$, s: $$mdi:mouse$$}
    '&mkp MB5': {t: $$mdi:arrow-u-right-top$$, s: $$mdi:mouse$$}


    # BLUETOOTH
    '&bt_sel 0': 'BT 1'
    '&bt_sel 1': 'BT 2'
    '&bt_sel 2': 'BT 3'
    '&bt_sel 3': 'BT 4'
    '&bt_sel 4': 'BT 5'

    '&bt BT_PRV':
      shifted: $$mdi:bluetooth-connect$$
      tap: ''
      hold: $$mdi:arrow-up-bold$$

    '&bt BT_NXT':
      shifted: $$mdi:bluetooth-connect$$
      tap: ''
      hold: $$mdi:arrow-down-bold$$

    '&out OUT_TOG':
      shifted: $$mdi:usb$$
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$


    # RGB
    '&rgb_ug RGB_TOG': '$$mdi:lightbulb-on-outline$$'
    '&rgb_ug RGB_EFF': '$$mdi:palette-swatch-outline$$'
    '&rgb_ug RGB_EFR': '$$mdi:palette-swatch-outline$$'
    '&rgb_ug RGB_BRI': '$$mdi:brightness-7$$'
    '&rgb_ug RGB_BRD': '$$mdi:brightness-4$$'


    '&none': {t: $$mdi:minus-circle-outline$$, type: none}
    '&bootloader': $$mdi:progress-download$$
    '&sys_reset': $$mdi:backup-restore$$
    '&soft_off': $$mdi:power$$
    '&caps_word': $$mdi:alpha-w-box$$


  sticky_label: $$mdi:gesture-tap-hold$$
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend: {t: ▽, type: trans}
  layer_legend_map: {}
  mark_alternate_layer_activators: true
  modifier_fn_map:
  left_ctrl: LCTRL
  right_ctrl: RCTRL
  left_shift: LSHFT
  right_shift: RSHFT
  left_alt: ALT
  right_alt: ALTGR
  left_gui: $$mdi:microsoft-windows$$
  right_gui: $$mdi:microsoft-windows$$
  keycode_combiner: '{mods}+{key}'
  mod_combiner: '{mod_1}+{mod_2}'
  special_combinations:
    left_ctrl+left_alt+left_gui+left_shift: Hyper
    left_ctrl+left_alt+left_shift: Meh


  # --- KEYCODES DE QMK ---
  qmk_remove_keycode_prefix:
  - KC_
  qmk_keycode_map:

    XXXXXXX: ''
    'NO': ''
    MINUS: '-'
    MINS: '-'
    EQUAL: '='
    EQL: '='
    LEFT_BRACKET: '['
    LBRC: '['
    RIGHT_BRACKET: ']'
    RBRC: ']'
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SCLN: ;
    QUOTE: ''''
    QUOT: ''''
    GRAVE: '`'
    GRV: '`'
    COMMA: ','
    COMM: ','
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: '~'
    TILD: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    LCBR: '{'
    RIGHT_CURLY_BRACE: '}'
    RCBR: '}'
    PIPE: '|'
    COLON: ':'
    COLN: ':'
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    RABK: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
    HOME: $$mdi:arrow-collapse-left$$
    END: $$mdi:arrow-collapse-right$$


  # --- KEYCODES DE ZMK ---
  zmk_remove_keycode_prefix:
  - ES_

  zmk_keycode_map:

    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: {t: '-', s: _}
    UNDERSCORE: _
    UNDER: _
    SLASH: '/'
    FSLH: '/'
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: {t: \, s: '|'}
    BSLH: {t: \, s: '|'}
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: {t: ;, s: ':'}
    SEMI: {t: ;, s: ':'}
    COLON: ':'
    SINGLE_QUOTE: {t: '''', s: '"'}
    SQT: {t: '''', s: '"'}
    APOSTROPHE: <
    APOS: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    NOT: '¬'
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: {t: ., s: ':'}
    COMMA: {t: ',', s: ;}
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: {t: '`', s: '~'}
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
    INVERTED_QUESTION: '¿'
    N1: {t: 1, s: '!'}
    N2: {t: 2, s: '"'}
    N3: {t: 3, s: '#'}
    N4: {t: 4, s: '$'}
    N5: {t: 5, s: '%'}
    N6: {t: 6, s: '&'}
    N7: {t: 7, s: '/'}
    N8: {t: 8, s: '('}
    N9: {t: 9, s: ')'}
    N0: {t: 0, s: '='}
    KP_DIVIDE: '/'
    KP_MINUS: '-'
    KP_MULTIPLY: '*'
    KP_PLUS: '+'
    KP_DOT: '.'
    KP_ENTER: {tap: $$mdi:keyboard-return$$, type: enter}

    LCTRL: LCTRL
    LEFT_CONTROL: LCTRL
    LALT: ALT
    LEFT_ALT: ALT
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LEFT_SHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LCMD: $$mdi:apple-keyboard-command$$
    LEFT_GUI: $$mdi:microsoft-windows$$
    LGUI: $$mdi:microsoft-windows$$
    LWIN: $$mdi:microsoft-windows$$
    RWIN: $$mdi:microsoft-windows$$
    RIGHT_GUI: $$mdi:microsoft-windows$$
    RIGHT_WIN: $$mdi:microsoft-windows$$
    RGUI: $$mdi:microsoft-windows$$
    RCTRL: RCTRL
    RIGHT_CONTROL: RCTRL
    RALT: ALTGR
    RIGHT_ALT: ALTGR
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RIGHT_SHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RCMD: $$mdi:apple-keyboard-command$$
    RG: $$mdi:apple-keyboard-command$$

    PSCRN: $$mdi:printer-outline$$
    RIGHT_COMMAND: $$mdi:apple-keyboard-command$$
    PAGE_UP: $$mdi:chevron-double-up$$
    PAGE_DOWN: $$mdi:chevron-double-down$$
    INSERT: Ins
    LS(LC(LALT)): $$mdi:star-three-points$$
    UP: $$mdi:arrow-up-bold$$
    UP_ARROW: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    DOWN_ARROW: $$mdi:arrow-down-bold$$
    LEFT_ARROW: $$mdi:arrow-left-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$
    RIGHT_ARROW: $$mdi:arrow-right-bold$$
    ENTER: {tap: $$mdi:keyboard-return$$, type: enter}
    RET: {tap: $$mdi:keyboard-return$$, type: enter}
    ESC: $$mdi:keyboard-esc$$
    ESCAPE: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE: {type: backspace, t: $$mdi:backspace$$}
    BSPC: {type: backspace, t: $$mdi:backspace$$}
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$
    C_VOLUME_UP: $$mdi:volume-high$$
    C_VOLUME_DOWN: $$mdi:volume-low$$
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$
    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$
    C_BRI_UP: $$mdi:brightness-5$$
    C_BRIGHTNESS_INC: $$mdi:brightness-5$$
    C_BRI_DN: $$mdi:brightness-7$$
    C_BRI_DEC: $$mdi:brightness-7$$
    C_BRIGHTNESS_DEC: $$mdi:brightness-7$$
    C_POWER: $$mdi:power-standby$$
    C_AL_LOCK: $$mdi:lock$$
    K_CANCEL: $$mdi:close-box$$
    K_FIND: $$mdi:apple-finder$$
    K_APP: $$mdi:menu$$
    K_MUTE2: $$mdi:volume-off$$
    K_VOLUME_UP2: $$mdi:volume-high$$
    K_VOLUME_DOWN2: $$mdi:volume-low$$
    K_PLAY_PAUSE: $$mdi:play-pause$$
    C_PLAY_PAUSE: $$mdi:play-pause$$
    K_PP: $$mdi:play-pause$$
    C_PP: $$mdi:play-pause$$
    K_NEXT: $$mdi:skip-next$$
    K_PREVIOUS: $$mdi:skip-previous$$
    C_PREVIOUS: $$mdi:skip-previous$$
    C_RW: $$mdi:rewind$$
    C_FF: $$mdi:fast-forward$$
    C_AL_CALC: $$mdi:calculator$$
    N_TILDE: Ñ
    HOME: $$mdi:arrow-collapse-left$$
    END: $$mdi:arrow-collapse-right$$


  # --- COMBOS ---

  zmk_combos:

    Toggle_Qwerty: {a: "left", o: 0.25}
    Toggle_SYM_NUM: {a: "right", o: 0.25}
    L_BSPC: {a: "top", o: 0.25}
    R_ESC: {a: "top", o: 0.25}
    BtCLR: {a: "right", o: 0.3}
    R_IQST: {a: "right"}
    R_QST: {a: "left"}
    R_PAR: {a: "right"}
    L_PAR: {a: "left"}

  zmk_preamble: '#define KEYMAP_DRAWER'
  zmk_additional_includes: []
